spring:
  application:
    name: chatting_app

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: chat
    producer:
      bootstrap-servers: localhost:9092

  data:
    mongodb:
      uri: mongodb://localhost:27017/chatting_app

