spring:
  application:
    name: chatting_app

  main:
    web-application-type: servlet

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: chat
    producer:
      bootstrap-servers: localhost:9092

  data:
    mongodb:
      uri: ${MONGODB_URL}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chattingApp
    username: root
    password: ${MYSQL_PASSWORD}

